discord:
  whitelist: true #Whether or not users can whitelist using their usernames (check plugin page for more info).
  token: placeholder #Your Discord bot token used to run the bot. Learn more about it here: https://docs.google.com/document/d/1qWs3M-2j3061bmvbBR75kZvd2fF5mQZpHM5AqghOD8Q/edit?usp=sharing
  channelID: placeholder #The ChannelID of Discord channel used for whitelisting users.

zombies:
  spawn: true #Wether or not zombies spawn on player death.
  pickup items: true #Wether or not the zombies can pickup items.
  strength: 1 #What level of strength the zombies have. Use 0 for no strength.

lightning: true #Whether or not lightning spawns on player death.

teleport: true #Whether or not spectators can teleport using /teleport.